name: 'TextNow Protect Number'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # 时间是按UTC设置的，实际执行时间，则自动按东八区执行
    # 即+8小时，故实际执行时间为：8点，20点
    - cron: 0 0,12 * * *

jobs:
  textnow:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7]
        #python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
      

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        playwright install
        pip install playwright==1.8.0a1
    
    # TextNow保号任务
    - name: TextNow protect number
      env:
        TEXTNOW_USERNAME: ${{ secrets.TEXTNOW_USERNAME }}
        TEXTNOW_PASSWORD: ${{ secrets.TEXTNOW_PASSWORD }}
        TEXTNOW_RECIPIENT: ${{ secrets.TEXTNOW_RECIPIENT }}
        TEXTNOW_MESSAGE: ${{ secrets.TEXTNOW_MESSAGE }}
      run: |
        python scripts/_textnow.py
